# Generated by Django 6.1.1 on 2026-09-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EvaluationForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="This field should be encrypted in a production environment.",
                        max_length=100,
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="This field should be encrypted in a production environment.",
                        max_length=100,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="This field should be encrypted in a production environment.",
                        max_length=254,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        help_text="Department within the organization", max_length=150
                    ),
                ),
                ("team_size", models.IntegerField(help_text="Size of the team")),
                (
                    "score_trust",
                    models.IntegerField(help_text="Trust in team members (1-5)"),
                ),
                (
                    "score_speaking_up",
                    models.IntegerField(
                        help_text="Comfort in speaking up without fear of retaliation (1-5)"
                    ),
                ),
                (
                    "score_inclusion",
                    models.IntegerField(
                        help_text="Feeling of inclusion and belonging (1-5)"
                    ),
                ),
                ("additional_feedback", models.TextField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Psychological Safety Evaluation",
                "verbose_name_plural": "Psychological Safety Evaluations",
            },
        ),
    ]
