# Generated by Django 6.1.1 on 2026-09-16 18:34

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="hero_subtitle",
            field=models.TextField(
                default="O cultură a învățării înlocuiește cultura vinovăției. Află cum poți construi echipe performante.",
                help_text="Subtitlul explicativ.",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_title",
            field=models.CharField(
                default="Impactul siguranței psihologice asupra performanței și inovației",
                help_text="Mesajul principal clar.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="philosophy_statement",
            field=wagtail.fields.RichTextField(
                default="<p>Siguranța psihologică nu este un lux, ci o necesitate strategică asumată de la nivel de management.</p>",
                help_text="Declarația despre rolul managementului în siguranța psihologică.",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="services",
            field=wagtail.fields.StreamField(
                [("service", 2)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    1: ("wagtail.blocks.TextBlock", (), {"required": True}),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1)]],
                        {"icon": "cog"},
                    ),
                },
                null=True,
            ),
        ),
    ]
